---
title: "modelSelection"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{modelSelection}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(parafac4microbiome)
library(dplyr)
library(ggplot2)
library(ggpubr)
```

```{r Fujita num comp selection}
# Setup
minNumComponents = 1
maxNumComponents = 3
numRepetitions = 25 # number of randomly initialized models
numFolds = 50 # number of jack-knifed models
ctol = 1e-6
maxit = 500
numCores=32

colourCols = c("", "Genus", "")
legendTitles = c("", "Genus", "")
xLabels = c("Replicate", "Feature index", "Time point")
legendColNums = c(0,5,0)
arrangeModes = c(FALSE, TRUE, FALSE)
continuousModes = c(FALSE,FALSE,TRUE)

# Preprocess
processedFujita = processDataCube(Fujita2023, sparsityThreshold=0.99, centerMode=1, scaleMode=2)

# For computational purposes we deviate from the default settings
assessment = assessNumComponents(processedFujita$data,
                                 minNumComponents,
                                 maxNumComponents,
                                 numRepetitions,
                                 ctol=ctol,
                                 maxit=maxit,
                                 numCores=numCores)

plotModelMetric(assessment$metrics, "numIterations")
plotModelMetric(assessment$metrics, "SSE")
plotModelMetric(assessment$metrics, "CORCONDIA")
plotModelMetric(assessment$metrics, "varExp")

# Model stability check using jack-knifing
for(f in minNumComponents:maxNumComponents){
  output = modelStabilityCheck(processedFujita$data,
                               processedFujita$mode1,
                               numComponents=f,
                               numFolds=numFolds,
                               numCores=numCores)
  print(plotModelStability(output, processedFujita,colourCols, legendTitles, xLabels, legendColNums, arrangeModes,
                           overallTitle = paste0("Jack-knifed Fujita2023, numFolds=", numFolds)))
}

# Tucker congruence coefficients
for(f in 2:3){
  print(plotModelTCCs(assessment$metrics$TCC[[f]]))
  print(plotOverallTCCs(assessment$metrics$TCC[[f]]))
}

# Here we decide on selecting the best 3-component model, i.e. explaining the largest amount of variation.
# Alternative: select based on maximum CORCONDIA.
numComponents = 3
modelChoice = which(assessment$metrics$varExp[,numComponents] == max(assessment$metrics$varExp[,numComponents]))
finalModel = assessment$models[[numComponents]][[modelChoice]]

# Convert model output to plottable data
metadataPerMode = list(processedFujita$mode1, processedFujita$mode2, processedFujita$mode3)
convertedModel = convertModelFormat(finalModel, metadataPerMode)

plotPARAFACmodel(convertedModel, colourCols, legendTitles, xLabels, legendColNums, arrangeModes,
  continuousModes = c(FALSE,FALSE,TRUE),
  overallTitle = "Fujita PARAFAC model")

# Due to the random initializations, this model may be slightly different from the paper.
```

```{r Shao comp selection}
# Setup
# For computational purposes we deviate from the default settings
minNumComponents = 1
maxNumComponents = 3
numRepetitions = 25 # number of randomly initialized models
numFolds = 50 # number of jack-knifed models
ctol=1e-6 # this is a really bad setting but is needed to save computational time

colourCols = c("Delivery_mode", "phylum", "")
legendTitles = c("Delivery mode", "Phylum", "")
xLabels = c("Subject index", "Feature index", "Time index")
legendColNums = c(3,5,0)
arrangeModes = c(TRUE, TRUE, FALSE)
continuousModes = c(FALSE,FALSE,TRUE)

# Pre-process the data
processedShao = processDataCube(Shao2019, sparsityThreshold=0.9, considerGroups=TRUE, groupVariable="Delivery_mode", centerMode=1, scaleMode=2)

assessment = assessNumComponents(processedShao$data,
                                 minNumComponents,
                                 maxNumComponents,
                                 numRepetitions,
                                 ctol,
                                 maxit,
                                 numCores=32)

plotModelMetric(assessment$metrics, "numIterations")
plotModelMetric(assessment$metrics, "SSE")
plotModelMetric(assessment$metrics, "CORCONDIA")
plotModelMetric(assessment$metrics, "varExp")

# Model stability check using jack-knifing
for(f in minNumComponents:maxNumComponents){
  output = modelStabilityCheck(processedShao$data,
                               processedShao$mode1,
                               numComponents=f,
                               numFolds=numFolds,
                               considerGroups=TRUE,
                               groupVariable="Delivery_mode",
                               ctol,
                               maxit=250,
                               numCores=32)
  print(plotModelStability(output, processedShao, colourCols, legendTitles, xLabels, legendColNums, arrangeModes,
                           overallTitle = paste0("Jack-knifed Shao2019, numFolds=", numFolds)))
}

# Tucker congruence coefficients
plotModelTCCs(assessment$metrics$TCC[[2]])
plotOverallTCCs(assessment$metrics$TCC[[2]])

# Here we decide on selecting the best 2-component model, i.e. explaining the largest amount of variation.
# Alternative: select based on maximum CORCONDIA.
numComponents = 2
modelChoice = which(assessment$metrics$varExp[,numComponents] == max(assessment$metrics$varExp[,numComponents]))
finalModel = assessment$models[[numComponents]][[modelChoice]]

metadataPerMode = list(processedShao$mode1, processedShao$mode2, processedShao$mode3)
convertedModel = convertModelFormat(finalModel, metadataPerMode)

plotPARAFACmodel(convertedModel,
  colourCols,
  legendTitles,
  xLabels,
  legendColNums,
  arrangeModes,
  continuousModes,
  overallTitle = "Shao2019 PARAFAC model")
```

```{r vanderPloeg comp selection}
# Setup
# For computational purposes we deviate from the default settings
minNumComponents = 1
maxNumComponents = 3
numRepetitions = 10 # number of randomly initialized models
numFolds = 100 # number of jack-knifed models
ctol = 1e-6
maxit = 250

colourCols = c("RFgroup", "Phylum", "")
legendTitles = c("RF group", "Phylum", "")
xLabels = c("Subject index", "Feature index", "Time index")
legendColNums = c(2,5,0)
arrangeModes = c(TRUE, TRUE, FALSE)
continuousModes = c(FALSE,FALSE,TRUE)

# Preprocess the data
processedPloeg = processDataCube(vanderPloeg2024, sparsityThreshold=0.50, considerGroups=TRUE, groupVariable="RFgroup", centerMode=1, scaleMode=2)

assessment = assessNumComponents(processedPloeg$data,
                                 minNumComponents,
                                 maxNumComponents,
                                 numRepetitions,
                                 ctol,
                                 maxit,
                                 numCores=32)

plotModelMetric(assessment$metrics, "numIterations")
plotModelMetric(assessment$metrics, "SSE")
plotModelMetric(assessment$metrics, "CORCONDIA")
plotModelMetric(assessment$metrics, "varExp")

# Model stability check using jack-knifing
for(f in minNumComponents:maxNumComponents){
  output = modelStabilityCheck(processedPloeg$data,
                               processedPloeg$mode1,
                               numComponents=f,
                               numFolds=numFolds,
                               considerGroups=TRUE,
                               groupVariable="RFgroup",
                               ctol,
                               maxit,
                               numCores=32)
  print(plotModelStability(output, processedPloeg, colourCols, legendTitles, xLabels, legendColNums, arrangeModes,
                           overallTitle = paste0("Jack-knifed Ploeg2024, numFolds=", numFolds)))
}

# Tucker congruence coefficients
for(f in 2:3){
  print(plotModelTCCs(assessment$metrics$TCC[[f]]))
  print(plotOverallTCCs(assessment$metrics$TCC[[f]]))
}

# Here we decide on selecting the best 2-component model, i.e. explaining the largest amount of variation.
# Alternative: select based on maximum CORCONDIA.
numComponents = 2
modelChoice = which(assessment$metrics$varExp[,numComponents] == max(assessment$metrics$varExp[,numComponents]))
finalModel = assessment$models[[numComponents]][[modelChoice]]

metadataPerMode = list(processedPloeg$mode1, processedPloeg$mode2, processedPloeg$mode3)
convertedModel = convertModelFormat(finalModel, metadataPerMode)

plotPARAFACmodel(convertedModel,
  colourCols,
  legendTitles,
  xLabels,
  legendColNums,
  arrangeModes,
  continuousModes,
  overallTitle = "vanderPloeg2024 PARAFAC model")
```
