#' PARAFAC loss function calculation
#'
#' @param X Input data
#' @param Fac Fac object generated by the PARAFAC algorithm
#'
#' @return Scalar value of the loss function
#' @export
#'
#' @examples
#' A = array(rnorm(108*2), c(108,2))
#' B = array(rnorm(100*2), c(100,2))
#' C = array(rnorm(10*2), c(10,2))
#' X = reinflateTensor(A, B, C)
#' model = parafac(X, 2)
#' f = parafac_fun(X, model$Fac)
parafac_fun = function(X, Fac){
  Xhat = reinflateTensor(Fac[[1]], Fac[[2]], Fac[[3]], returnAsTensor=TRUE)
  f = rTensor::fnorm(Xhat - X)
  return(f)
}
