#' PARAFAC loss function calculation
#'
#' @param X Input data
#' @param Fac Fac object generated by the PARAFAC algorithm
#' @param lambdas If lambdas (from the kruskal tensor case) are generated to make the Fac norm 1, they can be supplied.
#'
#' @return Scalar value of the loss function
#' @export
#'
#' @examples
#' A = array(rnorm(108*2), c(108,2))
#' B = array(rnorm(100*2), c(100,2))
#' C = array(rnorm(10*2), c(10,2))
#' X = reinflateTensor(A, B, C)
#' model = parafac(X, 2)
#' f = parafac_fun(X, model$Fac)
parafac_fun = function(X, Fac, lambdas=NULL){
  if(!is.null(lambdas)){
    Fac[[length(Fac)+1]] = as.matrix(lambdas)
  }

  Xhat = reinflateFac(Fac, X, returnAsTensor=TRUE)
  f = rTensor::fnorm(Xhat - X)
  return(f)
}
